/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PairRouteImport } from './routes/pair'
import { Route as DesignLabRouteImport } from './routes/design-lab'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as ChatRouteImport } from './routes/_chat'
import { Route as ChatIndexRouteImport } from './routes/_chat.index'
import { Route as SettingsTrackersRouteImport } from './routes/settings.trackers'
import { Route as SettingsSourceControlRouteImport } from './routes/settings.source-control'
import { Route as SettingsProvidersRouteImport } from './routes/settings.providers'
import { Route as SettingsPreferencesRouteImport } from './routes/settings.preferences'
import { Route as SettingsKeybindingsRouteImport } from './routes/settings.keybindings'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings.integrations'
import { Route as SettingsGeneralRouteImport } from './routes/settings.general'
import { Route as SettingsExperimentsRouteImport } from './routes/settings.experiments'
import { Route as SettingsDiagnosticsRouteImport } from './routes/settings.diagnostics'
import { Route as SettingsConnectionsRouteImport } from './routes/settings.connections'
import { Route as SettingsArchivedRouteImport } from './routes/settings.archived'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as ProjectsProjectKeyRouteImport } from './routes/projects.$projectKey'
import { Route as ConnectCallbackRouteImport } from './routes/connect_.callback'
import { Route as ChatRepositoriesRouteImport } from './routes/_chat.repositories'
import { Route as ChatPullRequestsRouteImport } from './routes/_chat.pull-requests'
import { Route as ChatMemoryRouteImport } from './routes/_chat.memory'
import { Route as ChatThreadsPlanIdRouteImport } from './routes/_chat.threads.$planId'
import { Route as ChatSessionsThreadIdRouteImport } from './routes/_chat.sessions.$threadId'
import { Route as ChatPlansPlanIdRouteImport } from './routes/_chat.plans.$planId'
import { Route as ChatDraftDraftIdRouteImport } from './routes/_chat.draft.$draftId'
import { Route as ChatEnvironmentIdThreadIdRouteImport } from './routes/_chat.$environmentId.$threadId'
import { Route as ChatThreadsDraftDraftIdRouteImport } from './routes/_chat.threads.draft.$draftId'
import { Route as ChatPlansDraftDraftIdRouteImport } from './routes/_chat.plans.draft.$draftId'

const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PairRoute = PairRouteImport.update({
  id: '/pair',
  path: '/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignLabRoute = DesignLabRouteImport.update({
  id: '/design-lab',
  path: '/design-lab',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/design-lab.lazy').then((d) => d.Route))
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/_chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const SettingsTrackersRoute = SettingsTrackersRouteImport.update({
  id: '/trackers',
  path: '/trackers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSourceControlRoute = SettingsSourceControlRouteImport.update({
  id: '/source-control',
  path: '/source-control',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProvidersRoute = SettingsProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPreferencesRoute = SettingsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKeybindingsRoute = SettingsKeybindingsRouteImport.update({
  id: '/keybindings',
  path: '/keybindings',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsGeneralRoute = SettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsExperimentsRoute = SettingsExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDiagnosticsRoute = SettingsDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsConnectionsRoute = SettingsConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsArchivedRoute = SettingsArchivedRouteImport.update({
  id: '/archived',
  path: '/archived',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const ProjectsProjectKeyRoute = ProjectsProjectKeyRouteImport.update({
  id: '/projects/$projectKey',
  path: '/projects/$projectKey',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectCallbackRoute = ConnectCallbackRouteImport.update({
  id: '/connect_/callback',
  path: '/connect/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRepositoriesRoute = ChatRepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPullRequestsRoute = ChatPullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => ChatRoute,
} as any)
const ChatMemoryRoute = ChatMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => ChatRoute,
} as any)
const ChatThreadsPlanIdRoute = ChatThreadsPlanIdRouteImport.update({
  id: '/threads/$planId',
  path: '/threads/$planId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatSessionsThreadIdRoute = ChatSessionsThreadIdRouteImport.update({
  id: '/sessions/$threadId',
  path: '/sessions/$threadId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPlansPlanIdRoute = ChatPlansPlanIdRouteImport.update({
  id: '/plans/$planId',
  path: '/plans/$planId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatDraftDraftIdRoute = ChatDraftDraftIdRouteImport.update({
  id: '/draft/$draftId',
  path: '/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatEnvironmentIdThreadIdRoute =
  ChatEnvironmentIdThreadIdRouteImport.update({
    id: '/$environmentId/$threadId',
    path: '/$environmentId/$threadId',
    getParentRoute: () => ChatRoute,
  } as any)
const ChatThreadsDraftDraftIdRoute = ChatThreadsDraftDraftIdRouteImport.update({
  id: '/threads/draft/$draftId',
  path: '/threads/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPlansDraftDraftIdRoute = ChatPlansDraftDraftIdRouteImport.update({
  id: '/plans/draft/$draftId',
  path: '/plans/draft/$draftId',
  getParentRoute: () => ChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ChatIndexRoute
  '/connect': typeof ConnectRoute
  '/design-lab': typeof DesignLabRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/memory': typeof ChatMemoryRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/repositories': typeof ChatRepositoriesRoute
  '/connect/callback': typeof ConnectCallbackRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/experiments': typeof SettingsExperimentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/trackers': typeof SettingsTrackersRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/plans/$planId': typeof ChatPlansPlanIdRoute
  '/sessions/$threadId': typeof ChatSessionsThreadIdRoute
  '/threads/$planId': typeof ChatThreadsPlanIdRoute
  '/plans/draft/$draftId': typeof ChatPlansDraftDraftIdRoute
  '/threads/draft/$draftId': typeof ChatThreadsDraftDraftIdRoute
}
export interface FileRoutesByTo {
  '/connect': typeof ConnectRoute
  '/design-lab': typeof DesignLabRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/memory': typeof ChatMemoryRoute
  '/pull-requests': typeof ChatPullRequestsRoute
  '/repositories': typeof ChatRepositoriesRoute
  '/connect/callback': typeof ConnectCallbackRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/experiments': typeof SettingsExperimentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/trackers': typeof SettingsTrackersRoute
  '/': typeof ChatIndexRoute
  '/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/plans/$planId': typeof ChatPlansPlanIdRoute
  '/sessions/$threadId': typeof ChatSessionsThreadIdRoute
  '/threads/$planId': typeof ChatThreadsPlanIdRoute
  '/plans/draft/$draftId': typeof ChatPlansDraftDraftIdRoute
  '/threads/draft/$draftId': typeof ChatThreadsDraftDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_chat': typeof ChatRouteWithChildren
  '/connect': typeof ConnectRoute
  '/design-lab': typeof DesignLabRoute
  '/pair': typeof PairRoute
  '/settings': typeof SettingsRouteWithChildren
  '/usage': typeof UsageRoute
  '/_chat/memory': typeof ChatMemoryRoute
  '/_chat/pull-requests': typeof ChatPullRequestsRoute
  '/_chat/repositories': typeof ChatRepositoriesRoute
  '/connect_/callback': typeof ConnectCallbackRoute
  '/projects/$projectKey': typeof ProjectsProjectKeyRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/archived': typeof SettingsArchivedRoute
  '/settings/connections': typeof SettingsConnectionsRoute
  '/settings/diagnostics': typeof SettingsDiagnosticsRoute
  '/settings/experiments': typeof SettingsExperimentsRoute
  '/settings/general': typeof SettingsGeneralRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/keybindings': typeof SettingsKeybindingsRoute
  '/settings/preferences': typeof SettingsPreferencesRoute
  '/settings/providers': typeof SettingsProvidersRoute
  '/settings/source-control': typeof SettingsSourceControlRoute
  '/settings/trackers': typeof SettingsTrackersRoute
  '/_chat/': typeof ChatIndexRoute
  '/_chat/$environmentId/$threadId': typeof ChatEnvironmentIdThreadIdRoute
  '/_chat/draft/$draftId': typeof ChatDraftDraftIdRoute
  '/_chat/plans/$planId': typeof ChatPlansPlanIdRoute
  '/_chat/sessions/$threadId': typeof ChatSessionsThreadIdRoute
  '/_chat/threads/$planId': typeof ChatThreadsPlanIdRoute
  '/_chat/plans/draft/$draftId': typeof ChatPlansDraftDraftIdRoute
  '/_chat/threads/draft/$draftId': typeof ChatThreadsDraftDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/design-lab'
    | '/pair'
    | '/settings'
    | '/usage'
    | '/memory'
    | '/pull-requests'
    | '/repositories'
    | '/connect/callback'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/experiments'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/preferences'
    | '/settings/providers'
    | '/settings/source-control'
    | '/settings/trackers'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/plans/$planId'
    | '/sessions/$threadId'
    | '/threads/$planId'
    | '/plans/draft/$draftId'
    | '/threads/draft/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/connect'
    | '/design-lab'
    | '/pair'
    | '/settings'
    | '/usage'
    | '/memory'
    | '/pull-requests'
    | '/repositories'
    | '/connect/callback'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/experiments'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/preferences'
    | '/settings/providers'
    | '/settings/source-control'
    | '/settings/trackers'
    | '/'
    | '/$environmentId/$threadId'
    | '/draft/$draftId'
    | '/plans/$planId'
    | '/sessions/$threadId'
    | '/threads/$planId'
    | '/plans/draft/$draftId'
    | '/threads/draft/$draftId'
  id:
    | '__root__'
    | '/_chat'
    | '/connect'
    | '/design-lab'
    | '/pair'
    | '/settings'
    | '/usage'
    | '/_chat/memory'
    | '/_chat/pull-requests'
    | '/_chat/repositories'
    | '/connect_/callback'
    | '/projects/$projectKey'
    | '/settings/appearance'
    | '/settings/archived'
    | '/settings/connections'
    | '/settings/diagnostics'
    | '/settings/experiments'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/keybindings'
    | '/settings/preferences'
    | '/settings/providers'
    | '/settings/source-control'
    | '/settings/trackers'
    | '/_chat/'
    | '/_chat/$environmentId/$threadId'
    | '/_chat/draft/$draftId'
    | '/_chat/plans/$planId'
    | '/_chat/sessions/$threadId'
    | '/_chat/threads/$planId'
    | '/_chat/plans/draft/$draftId'
    | '/_chat/threads/draft/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatRoute: typeof ChatRouteWithChildren
  ConnectRoute: typeof ConnectRoute
  DesignLabRoute: typeof DesignLabRoute
  PairRoute: typeof PairRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  UsageRoute: typeof UsageRoute
  ConnectCallbackRoute: typeof ConnectCallbackRoute
  ProjectsProjectKeyRoute: typeof ProjectsProjectKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pair': {
      id: '/pair'
      path: '/pair'
      fullPath: '/pair'
      preLoaderRoute: typeof PairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-lab': {
      id: '/design-lab'
      path: '/design-lab'
      fullPath: '/design-lab'
      preLoaderRoute: typeof DesignLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat': {
      id: '/_chat'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/': {
      id: '/_chat/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/settings/trackers': {
      id: '/settings/trackers'
      path: '/trackers'
      fullPath: '/settings/trackers'
      preLoaderRoute: typeof SettingsTrackersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/source-control': {
      id: '/settings/source-control'
      path: '/source-control'
      fullPath: '/settings/source-control'
      preLoaderRoute: typeof SettingsSourceControlRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/providers': {
      id: '/settings/providers'
      path: '/providers'
      fullPath: '/settings/providers'
      preLoaderRoute: typeof SettingsProvidersRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/preferences': {
      id: '/settings/preferences'
      path: '/preferences'
      fullPath: '/settings/preferences'
      preLoaderRoute: typeof SettingsPreferencesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/keybindings': {
      id: '/settings/keybindings'
      path: '/keybindings'
      fullPath: '/settings/keybindings'
      preLoaderRoute: typeof SettingsKeybindingsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/general': {
      id: '/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SettingsGeneralRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/experiments': {
      id: '/settings/experiments'
      path: '/experiments'
      fullPath: '/settings/experiments'
      preLoaderRoute: typeof SettingsExperimentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/diagnostics': {
      id: '/settings/diagnostics'
      path: '/diagnostics'
      fullPath: '/settings/diagnostics'
      preLoaderRoute: typeof SettingsDiagnosticsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/connections': {
      id: '/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof SettingsConnectionsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/archived': {
      id: '/settings/archived'
      path: '/archived'
      fullPath: '/settings/archived'
      preLoaderRoute: typeof SettingsArchivedRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/projects/$projectKey': {
      id: '/projects/$projectKey'
      path: '/projects/$projectKey'
      fullPath: '/projects/$projectKey'
      preLoaderRoute: typeof ProjectsProjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect_/callback': {
      id: '/connect_/callback'
      path: '/connect/callback'
      fullPath: '/connect/callback'
      preLoaderRoute: typeof ConnectCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_chat/repositories': {
      id: '/_chat/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof ChatRepositoriesRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/pull-requests': {
      id: '/_chat/pull-requests'
      path: '/pull-requests'
      fullPath: '/pull-requests'
      preLoaderRoute: typeof ChatPullRequestsRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/memory': {
      id: '/_chat/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof ChatMemoryRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/threads/$planId': {
      id: '/_chat/threads/$planId'
      path: '/threads/$planId'
      fullPath: '/threads/$planId'
      preLoaderRoute: typeof ChatThreadsPlanIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/sessions/$threadId': {
      id: '/_chat/sessions/$threadId'
      path: '/sessions/$threadId'
      fullPath: '/sessions/$threadId'
      preLoaderRoute: typeof ChatSessionsThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plans/$planId': {
      id: '/_chat/plans/$planId'
      path: '/plans/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof ChatPlansPlanIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/draft/$draftId': {
      id: '/_chat/draft/$draftId'
      path: '/draft/$draftId'
      fullPath: '/draft/$draftId'
      preLoaderRoute: typeof ChatDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/$environmentId/$threadId': {
      id: '/_chat/$environmentId/$threadId'
      path: '/$environmentId/$threadId'
      fullPath: '/$environmentId/$threadId'
      preLoaderRoute: typeof ChatEnvironmentIdThreadIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/threads/draft/$draftId': {
      id: '/_chat/threads/draft/$draftId'
      path: '/threads/draft/$draftId'
      fullPath: '/threads/draft/$draftId'
      preLoaderRoute: typeof ChatThreadsDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/_chat/plans/draft/$draftId': {
      id: '/_chat/plans/draft/$draftId'
      path: '/plans/draft/$draftId'
      fullPath: '/plans/draft/$draftId'
      preLoaderRoute: typeof ChatPlansDraftDraftIdRouteImport
      parentRoute: typeof ChatRoute
    }
  }
}

interface ChatRouteChildren {
  ChatMemoryRoute: typeof ChatMemoryRoute
  ChatPullRequestsRoute: typeof ChatPullRequestsRoute
  ChatRepositoriesRoute: typeof ChatRepositoriesRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ChatEnvironmentIdThreadIdRoute: typeof ChatEnvironmentIdThreadIdRoute
  ChatDraftDraftIdRoute: typeof ChatDraftDraftIdRoute
  ChatPlansPlanIdRoute: typeof ChatPlansPlanIdRoute
  ChatSessionsThreadIdRoute: typeof ChatSessionsThreadIdRoute
  ChatThreadsPlanIdRoute: typeof ChatThreadsPlanIdRoute
  ChatPlansDraftDraftIdRoute: typeof ChatPlansDraftDraftIdRoute
  ChatThreadsDraftDraftIdRoute: typeof ChatThreadsDraftDraftIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatMemoryRoute: ChatMemoryRoute,
  ChatPullRequestsRoute: ChatPullRequestsRoute,
  ChatRepositoriesRoute: ChatRepositoriesRoute,
  ChatIndexRoute: ChatIndexRoute,
  ChatEnvironmentIdThreadIdRoute: ChatEnvironmentIdThreadIdRoute,
  ChatDraftDraftIdRoute: ChatDraftDraftIdRoute,
  ChatPlansPlanIdRoute: ChatPlansPlanIdRoute,
  ChatSessionsThreadIdRoute: ChatSessionsThreadIdRoute,
  ChatThreadsPlanIdRoute: ChatThreadsPlanIdRoute,
  ChatPlansDraftDraftIdRoute: ChatPlansDraftDraftIdRoute,
  ChatThreadsDraftDraftIdRoute: ChatThreadsDraftDraftIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsArchivedRoute: typeof SettingsArchivedRoute
  SettingsConnectionsRoute: typeof SettingsConnectionsRoute
  SettingsDiagnosticsRoute: typeof SettingsDiagnosticsRoute
  SettingsExperimentsRoute: typeof SettingsExperimentsRoute
  SettingsGeneralRoute: typeof SettingsGeneralRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsKeybindingsRoute: typeof SettingsKeybindingsRoute
  SettingsPreferencesRoute: typeof SettingsPreferencesRoute
  SettingsProvidersRoute: typeof SettingsProvidersRoute
  SettingsSourceControlRoute: typeof SettingsSourceControlRoute
  SettingsTrackersRoute: typeof SettingsTrackersRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsArchivedRoute: SettingsArchivedRoute,
  SettingsConnectionsRoute: SettingsConnectionsRoute,
  SettingsDiagnosticsRoute: SettingsDiagnosticsRoute,
  SettingsExperimentsRoute: SettingsExperimentsRoute,
  SettingsGeneralRoute: SettingsGeneralRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsKeybindingsRoute: SettingsKeybindingsRoute,
  SettingsPreferencesRoute: SettingsPreferencesRoute,
  SettingsProvidersRoute: SettingsProvidersRoute,
  SettingsSourceControlRoute: SettingsSourceControlRoute,
  SettingsTrackersRoute: SettingsTrackersRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ChatRoute: ChatRouteWithChildren,
  ConnectRoute: ConnectRoute,
  DesignLabRoute: DesignLabRoute,
  PairRoute: PairRoute,
  SettingsRoute: SettingsRouteWithChildren,
  UsageRoute: UsageRoute,
  ConnectCallbackRoute: ConnectCallbackRoute,
  ProjectsProjectKeyRoute: ProjectsProjectKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
